-- Sentinel (Limey Guard) schema patch.
--
-- cmd/server's bootstrap flow writes audit rows where `detail` is only
-- set for some action types (e.g. admin.create passes a payload map,
-- bootstrap-related seeding passes nil). The original DDL made the
-- column NOT NULL, which crashed bootstrap with:
--
--   ERROR: null value in column "detail" of relation "audit_log"
--          violates not-null constraint (SQLSTATE 23502)
--
-- Widening the column to be nullable matches the Go code, which treats
-- detail as optional, and keeps DB mirrors versions-in-sync with the
-- out-of-band ALTER we already ran on the live database.
ALTER TABLE audit_log ALTER COLUMN detail DROP NOT NULL;
