import { mkdirSync, readdirSync, writeFileSync } from "fs";

const emojis = readdirSync("assets/emojis");

const names = emojis
    .filter(f => f !== "README.md")
    .map(f => f.replace(/\.[^/.]+$/, ""))
    .map(JSON.stringify);

mkdirSync("dist/types", { recursive: true });

writeFileSync("dist/types/emojis.d.ts", `
// This file is auto-generated by scripts/genTypes.mjs
// Do not edit this file directly!

import type { LiteralUnion } from "type-fest";
export type EmojiName = LiteralUnion<${names.join(" | ")}, string>;
`);
