DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS expressions;
DROP TABLE IF EXISTS expressionUses;
DROP TABLE IF EXISTS stickyRoles;
DROP TABLE IF EXISTS linkedGitHubs;
DROP TABLE IF EXISTS userAvatarEmojis;
DROP TABLE IF EXISTS xp;
